In [2]:
## Numpy array and basics

In [1]:
import numpy as np

In [5]:
## creating array from list

In [4]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)


arr_2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3 4 5]
 [1 2 3 4 5]]


### List vs Numpy

In [10]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

np_array = np.array([1,2,3])
print("numpy array multiplication", np_array*2)


import time

start = time.time()
py_list = [i*2 for i in range(10000)]
print("python list time", time.time()-start)

start = time.time()
np_array = np.array([i for i in range(10000)])
np_array = np_array * 2
print("numpy array time", time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]
python list time 0.0006954669952392578
numpy array time 0.00160980224609375


### creating array from scratch


In [13]:
zeroes  = np.zeros((3, 4))
print("zeroes array", zeroes)


ones = np.ones((2,3))
print("ones array", ones)

zeroes array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array [[1. 1. 1.]
 [1. 1. 1.]]
