In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
sales_data = np.array([[1, 15000, 18000, 25000],
                      [2,12000, 14000, 19000],
                      [2, 20000, 23000, 30000],
                      [3, 18000, 21000, 27000],
                      [4, 16000, 20500, 23000]])

print("===== Sales Data =====")
print(sales_data.shape)
print(sales_data[:3,])

===== Sales Data =====
(5, 4)
[[    1 15000 18000 25000]
 [    2 12000 14000 19000]
 [    2 20000 23000 30000]]


In [10]:
print("\n ======== Total Sales ========")
print(sales_data[:, 1:].sum(axis=1))


 ======== Total Sales ========
[58000 45000 73000 66000 59500]


In [12]:
print(sales_data[:, 1:].min(axis=1))

[15000 12000 20000 18000 16000]


In [14]:
avg_sales = np.mean(sales_data[:, 1:], axis=1)
print("Average sales per region:", avg_sales)

Average sales per region: [19333.33333333 15000.         24333.33333333 22000.
 19833.33333333]
