In [2]:
## Numpy array and basics

In [1]:
import numpy as np

In [5]:
## creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)


arr_2d = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print("2D Array:", arr_2d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3 4 5]
 [1 2 3 4 5]]


### List vs Numpy

In [3]:
py_list = [1,2,3]
print("python list multiplication", py_list*2)

np_array = np.array([1,2,3])
print("numpy array multiplication", np_array*2)


import time

start = time.time()
py_list = [i*2 for i in range(10000)]
print("python list time", time.time()-start)

start = time.time()
np_array = np.array([i for i in range(10000)])
np_array = np_array * 2
print("numpy array time", time.time()-start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]
python list time 0.0005519390106201172
numpy array time 0.0009663105010986328


### creating array from scratch


In [19]:
zeroes  = np.zeros((3, 4))
print("zeroes array", zeroes)


ones = np.ones((2,3))
print("ones array", ones)


full = np.full((6,6), 6)
print("full array", full)


random = np.random.random((2,3))
print("random array", random)

sequence = np.arange(0, 10, 2)
print("sequence array", sequence)

zeroes array [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array [[1. 1. 1.]
 [1. 1. 1.]]
full array [[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]
random array [[0.69840455 0.84900273 0.80354554]
 [0.24932491 0.42622514 0.70799919]]
sequence array [0 2 4 6 8]


## Vector and Tensor

In [5]:
vector = np.array([1,2,3])
print("vector", vector)

tensor = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])

print("tensor", tensor)

vector [1 2 3]
tensor [[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]


### Array Properties

In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print("shape of arr", arr.shape)

print("number of dimensions", arr.ndim)

print("size of array", arr.size)

print ("data type", arr.dtype)

shape of arr (2, 3)
number of dimensions 2
size of array 6
data type int64


### Array Reshaping

In [11]:
arr = np.arange(12)
print("Original array", arr)

reshaped = arr.reshape((3,4))
print("Reshaped array", reshaped)

flattened = reshaped.flatten()
print("Flattened array", flattened)

# returns view instead of copy
ravelled = reshaped.ravel()
print("Ravelled array", ravelled)


#transpose

transpose = reshaped.T
print("Transposed array", transpose)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
