## Numpy Array Operations


In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic slicing", arr[2:7])
print("Slicing with step", arr[2:8:2])
print("with negative indexing", arr[-5:-1])

Basic slicing [3 4 5 6 7]
Slicing with step [3 5 7]
with negative indexing [5 6 7 8]


In [3]:
arr_2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("specific element", arr_2d[0,2])
print("entire row", arr_2d[1])
print("entire row", arr_2d[:, 1])

specific element 3
entire row [ 6  7  8  9 10]
entire row [ 2  7 12]


### Sorting


In [4]:
unsorted = np.array([3,7,1,9,4,2,9,6])
print("Sorted Array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,7,1],
                            [9,4,2],
                            [6,5,8]])
print("sorted 2d array by column", np.sort(arr_2d_unsorted, axis=0))


Sorted Array [1 2 3 4 6 7 9 9]
sorted 2d array by column [[3 4 1]
 [6 5 2]
 [9 7 8]]


### special

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even numbers:", even_numbers)


Even numbers: [ 2  4  6  8 10]


In [7]:
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

Numbers greater than 5: [ 6  7  8  9 10]


In [11]:
indices = [0, 2, 4]
print("Elements at indices 0, 2, and 4:", numbers[indices])

where_result = np.where(numbers > 5)
print("Indices of elements greater than 5:", numbers[where_result])

Elements at indices 0, 2, and 4: [1 3 5]
Indices of elements greater than 5: [ 6  7  8  9 10]


In [14]:
condition_array = np.where(numbers > 5, True, False)
print("Condition array (True for >5):", condition_array)

Condition array (True for >5): [False False False False False  True  True  True  True  True]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1, arr2))
print("Combined array:", combined)

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
print("compatibilty shapes", a.shape == b.shape)

compatibilty shapes True


In [19]:
original = np.array([[1, 2, 3], [4, 5, 6]])
new_row = np.array([[7, 8, 9]])

with_new_row = np.vstack([original, new_row])
print("Array after adding new row:\n", with_new_row)    

new_column = np.array([[10], [11], [12]])
with_new_column = np.hstack([with_new_row, new_column])
print("Array after adding new column:\n", with_new_column)

Array after adding new row:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding new column:
 [[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [20]:
arr = np.array([1,2,3,4,5,6,7,8,9])
deleted = np.delete(arr, [0,5])
print("Array after deletion", deleted)

Array after deletion [2 3 4 5 7 8 9]
